language: shell

os: linux

before_install:
  - sudo add-apt-repository ppa:neovim-ppa/unstable -y
  - sudo apt-get update -q
  - sudo apt-get install neovim -y
  - curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
  - sudo apt install nodejs -y
script:
  bash NeoVimDeploy.sh -f

after_script:
  nvim  +CocInfo

notifications:
  email:
    on_success: never
