language: shell

os: linux

before_install:
  - sudo add-apt-repository ppa:neovim-ppa/unstable -y
  - sudo apt-get update -q
  - sudo apt-get install neovim -y
  #- curl -sL install-node.vercel.app/lts | sudo bash
script:
  bash NeoVimDeploy.sh -f

after_script:
  nvim 

notifications:
  email:
    on_success: never
