name: 'Check full deployment'
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-nvim-full-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install neovim and prerequisite
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update -q
          sudo apt-get install neovim -y
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt install nodejs -y

      - name: Run installing script
        run: bash NeoVimDeploy.sh -f

      - name:  Check coc plug installation
        run: |
          nvim --headless +CocOpenLog +qall && touch success
          find -maxdepth 1  -name "success"  | grep .
