name: 'Check nvim full deployment'
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: install neovim
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update -q
          sudo apt-get install neovim -y
          curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt install nodejs -y

      - name: Run install script
        run: bash NeoVimDeploy.sh -f

      - name: post check
        run: |
          nvim --headless +CocOpenLog +qall
          cd  /run/user/$UID
          ls 

